# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
   - script: |
          echo 'Running in workspace $(Pipeline.Workspace)'    
          echo 'Build.SourceBranchName: $(branch)'
          echo 'Build.SourceVersion: $(tag)'
          echo 'Build.SourcesDirectory: $(Build.SourcesDirectory)'
          echo 'Build.ArtifactStagingDirectory: $(build.artifactstagingdirectory)'
          echo 'Tags: $(tags)'          
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'mfsijvsdocimage'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
