parameters:
  dockerImage: 'none'
  buildEnv: 'none'
  dockerRegistry: 'none'

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        container:
          image: mfasiap/buildagentbaseimage

        steps:
        - script: VERSION_TAG=`git rev-parse --short HEAD` && echo "##vso[task.setvariable variable=versionTag]$VERSION_TAG"
          displayName: Fetch git revision to use from now on

        - task: Docker@2
          displayName: Build an image
          inputs:
            containerRegistry: |
              ${{ parameters.dockerRegistry }}
            repository: ${{ parameters.dockerImage }}
            command: build
            dockerfile: '$(Build.SourcesDirectory)/coursetune/Dockerfile'
            tags: |
              $(versionTag)
        - task: Docker@2
          displayName: Push image
          inputs:
            containerRegistry: |
              ${{ parameters.dockerRegistry }}
            repository: ${{ parameters.dockerImage }}
            command: push
            tags: |
              $(versionTag)
    
